name: Deploy Backend

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extract lowercase image name
        run: |
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/$OWNER_LOWER/trading-storm-backend" >> $GITHUB_ENV

      - name: Deploy to Lightsail
        env:
          HOST: ${{ secrets.LIGHTSAIL_HOST }}
          USER: ${{ secrets.LIGHTSAIL_USER }}
          SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST << EOF
            set -e

            echo "Pulling latest image"
            docker pull $IMAGE_NAME:latest

            echo "Restarting backend container"
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 3000:3000 $IMAGE_NAME:latest
          EOF
