name: Deploy Backend

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest Git tag
        id: get_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $LATEST_TAG"
          echo "VERSION_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Lowercase image name
        run: |
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/$OWNER_LOWER/trading-storm-backend" >> $GITHUB_ENV

      - name: Deploy to Lightsail
        env:
          HOST: ${{ secrets.LIGHTSAIL_HOST }}
          USER: ${{ secrets.LIGHTSAIL_USER }}
          SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          VERSION_TAG: ${{ env.VERSION_TAG }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST << EOF
            docker pull $IMAGE_NAME:$VERSION_TAG
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 3000:3000 $IMAGE_NAME:$VERSION_TAG
          EOF
